"""Add missing columns to Game table

Revision ID: 5b3111f61a42
Revises: c7ee3b09d973
Create Date: 2023-06-06 18:45:18.779731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3111f61a42'
down_revision = 'c7ee3b09d973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
